title: Jeff Alessandrelli
description: >- # ignore newlines until "baseurl:"
  Poetry.
baseurl: "" # subpath
url: "https://jeffalessandrelli.net"
tumblr_url: "https://jeffalessandrelli.tumblr.com/"
logo: "/assets/bg_stars.gif"
social:
  name: Jeff Alessandrelli
  links:
    - https://jeffalessandrelli.tumblr.com
google_site_verifications:

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-livereload
sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
