title: Jeff Alessandrelli
description: >- # this means to ignore newlines until "baseurl:"
  Poetry.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
tumblr_url: "http://jeffalessandrelli.tumblr.com/"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-livereload

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
